### ISSUE TITLE
Failed to process atomistic input file

### ISSUE THREAD

**Issue by yang-guoli** [owenvickery/cg2at#16]
hi, i run your code to convrt CG file to AA file, but it has error as follows:
![image](https://user-images.githubusercontent.com/73353085/162742313-34a20451-f860-4329-ad81-bf919e3d8991.png)

**Comment by yang-guoli** [comment]
@owenvickery Sorry. The above error occurred because I didn't read the run file carefully before specifying that the whole atomic structure was coarse-grained. Now I have specified the correct whole atomic structure and it works fine. But when I process the membrane, it says: DPSM is not in the fragment database! How do I generate DPSM fragments?

**Comment by owenvickery** [comment]
Hi, sorry for the slow reply. 
That error is due to there being different ways of compiling gromacs. To prevent gromacs from stealing all the resources you have to specify number of threads.  
I haven't thought of an easy way around this yet. The quickest way around is to remove the -nt or -ntmpi flags in the mdrun sections. They are all in the file "database/bin/gro.py".

**Comment by owenvickery** [comment]
I've removed all the -nt flags from the mdrun so should now run on all gromacs installs, with the caveat that gromacs will try to use all cores available.
